<<<<<<< HEAD

num_of_pennies = int(input("How many pennies would you like to convert?"))

dollar_bill_100 = int(num_of_pennies // 10000)
dollar_bill_50 = int(num_of_pennies // 5000)
dollar_bill_20 = int(num_of_pennies % 2000)
dollar_bill_10 = int(num_of_pennies % 1000)
dollar_bill_5 = int(num_of_pennies % 500)
dollar_bill_2 = int(num_of_pennies % 200)
dollar_bill_1 = int(num_of_pennies % 100)
half_dollar = int(num_of_pennies % .50)
quarter = int(num_of_pennies % .25)
dime = int(num_of_pennies % .10)
nickel = int(num_of_pennies % .5)
penny = int(num_of_pennies % 0.1)

print(f"{dollar_bill_100} 100, Dollar Bill ")
print(f"{dollar_bill_50} 50, Dollar Bill")
print(f"{dollar_bill_20} 20, Dollar Bill")
print(f"{dollar_bill_10} 10, Dollar Bill")
print(f"{dollar_bill_50} 5, Dollar Bill")
print(f"{dollar_bill_2} 2, Dollar Bill")
print(f"{dollar_bill_1} 1, Dollar Bill")
print(f"{half_dollar} 50, Cents")
print(f"{quarter} 25, Cents")
print(f"{dime} 10, Cents")
print(f"{nickel} 5, Cents")
print(f"{penny} 1, Cent")

print("Thank you have and have a good day.")
=======

num_of_pennies = int(input("How many pennies would you like to convert?"))

dollar_bill_100 = int(num_of_pennies // 10000)
dollar_bill_50 = int(num_of_pennies // 5000)
dollar_bill_20 = int(num_of_pennies % 2000)
dollar_bill_10 = int(num_of_pennies % 1000)
dollar_bill_5 = int(num_of_pennies % 500)
dollar_bill_2 = int(num_of_pennies % 200)
dollar_bill_1 = int(num_of_pennies % 100)
half_dollar = int(num_of_pennies % .50)
quarter = int(num_of_pennies % .25)
dime = int(num_of_pennies % .10)
nickel = int(num_of_pennies % .5)
penny = int(num_of_pennies % 0.1)

print(f"{dollar_bill_100} 100, Dollar Bill ")
print(f"{dollar_bill_50} 50, Dollar Bill")
print(f"{dollar_bill_20} 20, Dollar Bill")
print(f"{dollar_bill_10} 10, Dollar Bill")
print(f"{dollar_bill_50} 5, Dollar Bill")
print(f"{dollar_bill_2} 2, Dollar Bill")
print(f"{dollar_bill_1} 1, Dollar Bill")
print(f"{half_dollar} 50, Cents")
print(f"{quarter} 25, Cents")
print(f"{dime} 10, Cents")
print(f"{nickel} 5, Cents")
print(f"{penny} 1, Cent")

print("Thank you have and have a good day.")
>>>>>>> ba4b388bef6d2e75ff26c636f0835e8aaaa794d5
