# Generated by Django 6.0.3 on 2026-03-31 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_tier', models.CharField(choices=[('standard', 'Standard - Day Pass'), ('silver', 'Silver - Season Pass'), ('gold', 'Gold - Premium Season Pass'), ('platinum', 'Platinum - VIP All-Access')], default='standard', max_length=20)),
                ('daily_fastpass_limit', models.IntegerField(default=3)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attraction_type', models.CharField(choices=[('ride', 'Ride'), ('show', 'Show'), ('experience', 'Experience'), ('dining', 'Dining')], default='ride', max_length=20)),
                ('thrill_level', models.IntegerField(choices=[(1, 'Mild - All Ages'), (2, 'Moderate - Some Thrills'), (3, 'Thrilling - Not for the Faint of Heart'), (4, 'Extreme - Hold onto Your Ewok!')], default=1)),
                ('min_height_cm', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('current_wait_minutes', models.IntegerField(default=0)),
                ('is_operational', models.BooleanField(default=True)),
                ('fastpass_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='fastpass.themezone')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_fastpasses', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fastpass.attraction')),
            ],
            options={
                'ordering': ['attraction', 'start_time'],
                'unique_together': {('attraction', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='FastPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.attraction')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.guest')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.timeslot')),
            ],
            options={
                'verbose_name_plural': 'FastPasses',
                'ordering': ['-booking_date', 'time_slot__start_time'],
                'unique_together': {('guest', 'attraction', 'booking_date')},
            },
        ),
    ]
